version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENV=development
      - MYSQL_HOST=
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
    restart: unless-stopped
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
